name: "St Bakhita Parish"
description: "The official website of St Bakhita Parish, Lashibi"
url: "http://saintbakhita.com"
markdown: kramdown
permalink: pretty
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'changelog.txt', 'Dockerfile', 'Makefile', 'trashcan', 'Readme.txt']

# collections:
#  documents:
#   output: true